const PROGRAMS_DATA = [
  {
    "id": 1,
    "number": 1,
    "title": "Stack Implementation (Push, Pop, Show)",
    "category": "Stacks & Queues",
    "timeComplexity": "O(1) Push/Pop",
    "spaceComplexity": "O(MAX)",
    "aim": "Write a program to implement stack with push, pop and show operations.",
    "code": "#include<iostream.h>\n#include<conio.h>\n#define MAX 20\nint stack[MAX], top=-1;\nvoid push()\n{\n    int x;\n    if(top==MAX-1)\n    cout<<\"Stack Overflow\";\n    else\n    {\n        cout<<\"Enter element: \";\n        cin>>x;\n        stack[++top]=x;\n    }\n}\nvoid pop()\n{\n    if(top==-1)\n    cout<<\"Stack Underflow\";\n    else\n    cout<<\"Deleted element: \"<<stack[top--];\n}\nvoid show()\n{\n    int i;\n    if(top==-1)\n    cout<<\"Stack is empty\";\n    else\n    {\n        cout<<\"Stack: \";\n        for(i=top;i>=0;i--)\n        cout<<stack[i]<<\" \";\n    }\n}\nvoid main()\n{\n    int ch;\n    clrscr();\n    do\n    {\n        cout<<\"\\n\\n1.Push 2.Pop 3.Show 4.Exit\";\n        cout<<\"\\nEnter choice: \";\n        cin>>ch;\n        switch(ch)\n        {\n            case 1: push(); break;\n            case 2: pop(); break;\n            case 3: show(); break;\n            case 4: break;\n            default: cout<<\"Invalid choice\";\n        }\n    }while(ch!=4);\n    getch();\n}",
    "description": "A Stack is a Linear Data Structure that follows the LIFO (Last In First Out) principle. Elements can be added and removed only from one end called TOP.",
    "algorithmSteps": "1. Push: Check if top == MAX-1 (Overflow). If not, increment top and store element at stack[top].\n2. Pop: Check if top == -1 (Underflow). If not, access stack[top] and decrement top.\n3. Show: Loop from top down to 0 and print stack[i].",
    "sampleInput": "10, 25, 42, 7"
  },
  {
    "id": 2,
    "number": 2,
    "title": "Quick Sort Algorithm",
    "category": "Sorting",
    "timeComplexity": "O(n log n) avg, O(n\u00b2) worst",
    "spaceComplexity": "O(log n)",
    "aim": "Write a program to sort the given elements using Quick Sort algorithm.",
    "code": "#include<iostream.h>\n#include<conio.h>\nint a[50], n;\nvoid quicksort(int low,int high)\n{\n    int i=low, j=high, pivot=a[(low+high)/2], temp;\n    while(i<=j)\n    {\n        while(a[i]<pivot) i++;\n        while(a[j]>pivot) j--;\n        if(i<=j)\n        {\n            temp=a[i]; a[i]=a[j]; a[j]=temp;\n            i++; j--;\n        }\n    }\n    if(low<j) quicksort(low,j);\n    if(i<high) quicksort(i,high);\n}\nvoid main()\n{\n    int i;\n    clrscr();\n    cout<<\"Enter number of elements: \";\n    cin>>n;\n    cout<<\"Enter elements: \";\n    for(i=0;i<n;i++) cin>>a[i];\n    quicksort(0,n-1);\n    cout<<\"Sorted array: \";\n    for(i=0;i<n;i++) cout<<a[i]<<\" \";\n    getch();\n}",
    "description": "Quick Sort is a Divide-and-Conquer algorithm. It selects a pivot element and partitions the array such that elements smaller than pivot are on the left, and elements greater are on the right.",
    "algorithmSteps": "1. Choose pivot (middle element: a[(low+high)/2]).\n2. Initialize i = low, j = high.\n3. Increment i until a[i] >= pivot; Decrement j until a[j] <= pivot.\n4. If i <= j, swap a[i] and a[j], increment i, decrement j.\n5. Recursively sort left subarray (low to j) and right subarray (i to high).",
    "sampleInput": "35, 12, 89, 44, 2, 78, 23"
  },
  {
    "id": 3,
    "number": 3,
    "title": "Simple Queue (Insert, Delete, Show)",
    "category": "Stacks & Queues",
    "timeComplexity": "O(1) Insert/Delete",
    "spaceComplexity": "O(MAX)",
    "aim": "Write a program to implement simple queue with insert, delete and show operation.",
    "code": "#include<iostream.h>\n#include<conio.h>\n#define MAX 20\nint q[MAX], front=-1, rear=-1;\nvoid insert()\n{\n    int x;\n    if(rear==MAX-1)\n    cout<<\"Queue Overflow\";\n    else\n    {\n        cout<<\"Enter element: \";\n        cin>>x;\n        if(front==-1) front=0;\n        q[++rear]=x;\n    }\n}\nvoid del()\n{\n    if(front==-1 || front>rear)\n    cout<<\"Queue Underflow\";\n    else\n    {\n        cout<<\"Deleted element: \"<<q[front++];\n        if(front>rear) front=rear=-1;\n    }\n}\nvoid show()\n{\n    int i;\n    if(front==-1)\n    cout<<\"Queue is empty\";\n    else\n    {\n        cout<<\"Queue: \";\n        for(i=front;i<=rear;i++) cout<<q[i]<<\" \";\n    }\n}\nvoid main()\n{\n    int ch;\n    clrscr();\n    do\n    {\n        cout<<\"\\n\\n1.Insert 2.Delete 3.Show 4.Exit\";\n        cout<<\"\\nEnter choice: \";\n        cin>>ch;\n        switch(ch)\n        {\n            case 1: insert(); break;\n            case 2: del(); break;\n            case 3: show(); break;\n            case 4: break;\n            default: cout<<\"Invalid choice\";\n        }\n    }while(ch!=4);\n    getch();\n}",
    "description": "A Queue is a Linear Data Structure that follows the FIFO (First In First Out) principle. Elements are inserted at REAR and deleted from FRONT.",
    "algorithmSteps": "1. Insert: Check if rear == MAX-1 (Overflow). If front == -1 set front = 0. Increment rear and store element at q[rear].\n2. Delete: Check if front == -1 or front > rear (Underflow). Delete element at q[front++]. If front > rear, reset both to -1.\n3. Show: Display all elements from front to rear.",
    "sampleInput": "15, 30, 45, 60"
  },
  {
    "id": 4,
    "number": 4,
    "title": "Merge Sort Algorithm",
    "category": "Sorting",
    "timeComplexity": "O(n log n)",
    "spaceComplexity": "O(n)",
    "aim": "Merge Sort",
    "code": "#include<iostream.h>\n#include<conio.h>\nint a[50], temp[50], n;\nvoid merge(int low,int mid,int high)\n{\n    int i=low,j=mid+1,k=low;\n    while(i<=mid && j<=high)\n    {\n        if(a[i]<a[j]) temp[k++]=a[i++];\n        else temp[k++]=a[j++];\n    }\n    while(i<=mid) temp[k++]=a[i++];\n    while(j<=high) temp[k++]=a[j++];\n    for(i=low;i<=high;i++) a[i]=temp[i];\n}\nvoid mergesort(int low,int high)\n{\n    int mid;\n    if(low<high)\n    {\n        mid=(low+high)/2;\n        mergesort(low,mid);\n        mergesort(mid+1,high);\n        merge(low,mid,high);\n    }\n}\nvoid main()\n{\n    int i;\n    clrscr();\n    cout<<\"Enter number of elements: \";\n    cin>>n;\n    cout<<\"Enter elements: \";\n    for(i=0;i<n;i++) cin>>a[i];\n    mergesort(0,n-1);\n    cout<<\"Sorted array: \";\n    for(i=0;i<n;i++) cout<<a[i]<<\" \";\n    getch();\n}",
    "description": "Merge Sort is an efficient, stable, divide-and-conquer sorting algorithm. It divides the input array into two halves, recursively sorts them, and then merges the sorted halves.",
    "algorithmSteps": "1. Find middle point: mid = (low + high)/2.\n2. Call mergesort for first half (low to mid).\n3. Call mergesort for second half (mid+1 to high).\n4. Merge the two sorted halves into temporary array and copy back.",
    "sampleInput": "45, 18, 72, 30, 9, 56, 33"
  },
  {
    "id": 5,
    "number": 5,
    "title": "Infix to Postfix Conversion",
    "category": "Expressions",
    "timeComplexity": "O(n)",
    "spaceComplexity": "O(n)",
    "aim": "Infix to Postfix",
    "code": "#include<iostream.h>\n#include<conio.h>\n#include<string.h>\n#include<ctype.h>\nchar st[50], infix[50], postfix[50];\nint top=-1;\nint priority(char c)\n{\n    if(c=='+' || c=='-') return 1;\n    if(c=='*' || c=='/') return 2;\n    if(c=='^') return 3;\n    return 0;\n}\nvoid main()\n{\n    int i=0,j=0;\n    char c;\n    clrscr();\n    cout<<\"Enter infix expression: \";\n    cin>>infix;\n    while(infix[i]!='\\0')\n    {\n        c=infix[i];\n        if(isalnum(c))\n        postfix[j++]=c;\n        else if(c=='(')\n        st[++top]=c;\n        else if(c==')')\n        {\n            while(top!=-1 && st[top]!='(')\n            postfix[j++]=st[top--];\n            if(top!=-1) top--;\n        }\n        else\n        {\n            while(top!=-1 && priority(st[top])>=priority(c))\n            postfix[j++]=st[top--];\n            st[++top]=c;\n        }\n        i++;\n    }\n    while(top!=-1) postfix[j++]=st[top--];\n    postfix[j]='\\0';\n    cout<<\"Postfix expression: \"<<postfix;\n    getch();\n}",
    "description": "Infix to Postfix conversion uses an Operator Stack. Operands are directly added to the output postfix string, while operators are placed on the stack according to precedence.",
    "algorithmSteps": "1. Scan infix from left to right.\n2. If operand (alphanumeric), append to postfix.\n3. If '(', push to stack. If ')', pop and append until '(' is encountered.\n4. If operator: pop from stack while stack top has higher or equal precedence, then push operator.\n5. At end, pop all remaining operators from stack.",
    "sampleInput": "(A+B)*(C-D)^E"
  },
  {
    "id": 6,
    "number": 6,
    "title": "Bubble Sort Algorithm",
    "category": "Sorting",
    "timeComplexity": "O(n\u00b2)",
    "spaceComplexity": "O(1)",
    "aim": "Bubble Sort",
    "code": "#include<iostream.h>\n#include<conio.h>\nvoid main()\n{\n    int a[50],n,i,j,temp;\n    clrscr();\n    cout<<\"Enter number of elements: \";\n    cin>>n;\n    cout<<\"Enter elements: \";\n    for(i=0;i<n;i++) cin>>a[i];\n    for(i=0;i<n-1;i++)\n    for(j=0;j<n-i-1;j++)\n    if(a[j]>a[j+1])\n    {\n        temp=a[j]; a[j]=a[j+1]; a[j+1]=temp;\n    }\n    cout<<\"Sorted array: \";\n    for(i=0;i<n;i++) cout<<a[i]<<\" \";\n    getch();\n}",
    "description": "Bubble Sort repeatedly steps through the list, compares adjacent elements, and swaps them if they are in the wrong order. Pass after pass, the largest unsorted element bubbles up to its correct position.",
    "algorithmSteps": "1. For i = 0 to n-2 (passes):\n2.   For j = 0 to n-i-2 (adjacent comparisons):\n3.     If a[j] > a[j+1], swap a[j] and a[j+1].\n4. Array is completely sorted after n-1 passes.",
    "sampleInput": "64, 34, 25, 12, 22, 11, 90"
  },
  {
    "id": 7,
    "number": 7,
    "title": "Prefix Expression Evaluation",
    "category": "Expressions",
    "timeComplexity": "O(n)",
    "spaceComplexity": "O(n)",
    "aim": "Polish Notation (Prefix) Evaluation",
    "code": "#include<iostream.h>\n#include<conio.h>\n#include<ctype.h>\n#include<string.h>\nint st[50], top=-1;\nint power(int a,int b)\n{\n    int r=1,i;\n    for(i=0;i<b;i++) r=r*a;\n    return r;\n}\nint operation(int a,int b,char op)\n{\n    switch(op)\n    {\n        case '+': return a+b;\n        case '-': return a-b;\n        case '*': return a*b;\n        case '/': return a/b;\n        case '^': return power(a,b);\n    }\n    return 0;\n}\nvoid main()\n{\n    char exp[50],c;\n    int i,n,a,b;\n    clrscr();\n    cout<<\"Enter prefix expression (single digit operands): \";\n    cin>>exp;\n    n=strlen(exp);\n    for(i=n-1;i>=0;i--)\n    {\n        c=exp[i];\n        if(isdigit(c))\n        st[++top]=c-'0';\n        else\n        {\n            a=st[top--];\n            b=st[top--];\n            st[++top]=operation(a,b,c);\n        }\n    }\n    cout<<\"Result: \"<<st[top];\n    getch();\n}",
    "description": "Prefix expression (Polish Notation) evaluation scans from right to left. Operands are pushed onto an evaluation stack, and operators pop two operands, evaluate the result, and push it back.",
    "algorithmSteps": "1. Read prefix string from right to left (index n-1 down to 0).\n2. If character is digit, push (c - '0') onto stack.\n3. If operator: pop a = st[top--], pop b = st[top--], calculate result = operation(a, b, op), and push result back.\n4. Final answer is on top of stack.",
    "sampleInput": "+ * 2 3 4"
  },
  {
    "id": 8,
    "number": 8,
    "title": "Insertion Sort Algorithm",
    "category": "Sorting",
    "timeComplexity": "O(n\u00b2)",
    "spaceComplexity": "O(1)",
    "aim": "Write a program to sort the given elements using Insertion Sort algorithm.",
    "code": "#include<iostream.h>\n#include<conio.h>\nvoid main()\n{\n    int a[50],n,i,j,key;\n    clrscr();\n    cout<<\"Enter number of elements: \";\n    cin>>n;\n    cout<<\"Enter elements: \";\n    for(i=0;i<n;i++) cin>>a[i];\n    for(i=1;i<n;i++)\n    {\n        key=a[i];\n        j=i-1;\n        while(j>=0 && a[j]>key)\n        {\n            a[j+1]=a[j];\n            j--;\n        }\n        a[j+1]=key;\n    }\n    cout<<\"Sorted array: \";\n    for(i=0;i<n;i++) cout<<a[i]<<\" \";\n    getch();\n}",
    "description": "Insertion Sort builds the final sorted array one item at a time. It takes each element and inserts it into its proper sorted position among the previously sorted elements.",
    "algorithmSteps": "1. Loop i from 1 to n-1 (key = a[i]).\n2. Set j = i - 1.\n3. Move elements of a[0..i-1] that are greater than key to one position ahead (a[j+1] = a[j]).\n4. Insert key at its sorted position: a[j+1] = key.",
    "sampleInput": "12, 11, 13, 5, 6, 7"
  },
  {
    "id": 9,
    "number": 9,
    "title": "Tower of Hanoi Problem",
    "category": "Recursion",
    "timeComplexity": "O(2\u207f)",
    "spaceComplexity": "O(n)",
    "aim": "Tower of Hanoi",
    "code": "#include<iostream.h>\n#include<conio.h>\nvoid hanoi(int n,char source,char aux,char dest)\n{\n    if(n==1)\n    {\n        cout<<\"Move disk 1 from \"<<source<<\" to \"<<dest<<\"\\n\";\n        return;\n    }\n    hanoi(n-1,source,dest,aux);\n    cout<<\"Move disk \"<<n<<\" from \"<<source<<\" to \"<<dest<<\"\\n\";\n    hanoi(n-1,aux,source,dest);\n}\nvoid main()\n{\n    int n;\n    clrscr();\n    cout<<\"Enter number of disks: \";\n    cin>>n;\n    hanoi(n,'A','B','C');\n    getch();\n}",
    "description": "Tower of Hanoi is a mathematical puzzle with 3 pegs (Source A, Auxiliary B, Destination C) and n disks of different sizes. Rule: Only one disk can be moved at a time, and no larger disk may be placed on top of a smaller disk.",
    "algorithmSteps": "1. Move n-1 disks from Source to Auxiliary using Destination peg.\n2. Move the nth (largest) disk directly from Source to Destination.\n3. Move the n-1 disks from Auxiliary to Destination using Source peg.\nTotal moves required = 2^n - 1.",
    "sampleInput": "3"
  },
  {
    "id": 10,
    "number": 10,
    "title": "Selection Sort Algorithm",
    "category": "Sorting",
    "timeComplexity": "O(n\u00b2)",
    "spaceComplexity": "O(1)",
    "aim": "Write a program to sort the given elements using Selection Sort algorithm.",
    "code": "#include<iostream.h>\n#include<conio.h>\nvoid main()\n{\n    int a[50],n,i,j,min,temp;\n    clrscr();\n    cout<<\"Enter number of elements: \";\n    cin>>n;\n    cout<<\"Enter elements: \";\n    for(i=0;i<n;i++) cin>>a[i];\n    for(i=0;i<n-1;i++)\n    {\n        min=i;\n        for(j=i+1;j<n;j++)\n        if(a[j]<a[min]) min=j;\n        temp=a[i]; a[i]=a[min]; a[min]=temp;\n    }\n    cout<<\"Sorted array: \";\n    for(i=0;i<n;i++) cout<<a[i]<<\" \";\n    getch();\n}",
    "description": "Selection Sort divides the array into sorted and unsorted subarrays. It repeatedly finds the minimum element from the unsorted subarray and swaps it with the first unsorted element.",
    "algorithmSteps": "1. Loop i from 0 to n-2:\n2.   Assume min = i.\n3.   For j = i+1 to n-1: if a[j] < a[min], update min = j.\n4.   Swap a[i] with a[min].\n5. Repeat until array is sorted.",
    "sampleInput": "29, 10, 14, 37, 13"
  },
  {
    "id": 11,
    "number": 11,
    "title": "Linear Search Algorithm",
    "category": "Searching",
    "timeComplexity": "O(n)",
    "spaceComplexity": "O(1)",
    "aim": "Write a program to search the element in given array using linear search algorithm.",
    "code": "#include<iostream.h>\n#include<conio.h>\nvoid main()\n{\n    int a[50],n,key,i,found=0;\n    clrscr();\n    cout<<\"Enter number of elements: \";\n    cin>>n;\n    cout<<\"Enter elements: \";\n    for(i=0;i<n;i++) cin>>a[i];\n    cout<<\"Enter element to search: \";\n    cin>>key;\n    for(i=0;i<n;i++)\n    if(a[i]==key)\n    {\n        cout<<\"Element found at position \"<<i+1;\n        found=1;\n        break;\n    }\n    if(!found) cout<<\"Element not found\";\n    getch();\n}",
    "description": "Linear Search sequentially checks each element of the list until a match is found or the whole list has been searched.",
    "algorithmSteps": "1. Start from index 0.\n2. Compare search key with each element a[i].\n3. If a[i] == key: return position i+1 (found).\n4. If loop ends without match: element not found.",
    "sampleInput": "15, 5, 20, 35, 2, 42"
  },
  {
    "id": 12,
    "number": 12,
    "title": "Depth First Search (DFS)",
    "category": "Graphs",
    "timeComplexity": "O(V\u00b2)",
    "spaceComplexity": "O(V)",
    "aim": "DFS Graph Traversal",
    "code": "#include<iostream.h>\n#include<conio.h>\nint a[10][10], visited[10], n;\nvoid dfs(int v)\n{\n    int i;\n    visited[v]=1;\n    cout<<v<<\" \";\n    for(i=0;i<n;i++)\n    if(a[v][i] && !visited[i])\n    dfs(i);\n}\nvoid main()\n{\n    int i,j,start;\n    clrscr();\n    cout<<\"Enter number of vertices: \";\n    cin>>n;\n    cout<<\"Enter adjacency matrix:\\n\";\n    for(i=0;i<n;i++)\n    for(j=0;j<n;j++)\n    cin>>a[i][j];\n    for(i=0;i<n;i++) visited[i]=0;\n    cout<<\"Enter starting vertex (0 to \"<<n-1<<\"): \";\n    cin>>start;\n    cout<<\"DFS traversal: \";\n    dfs(start);\n    getch();\n}",
    "description": "Depth First Search (DFS) is a graph traversal algorithm that explores as far as possible along each branch before backtracking using recursion or an explicit stack.",
    "algorithmSteps": "1. Mark current vertex v as visited and print v.\n2. For each adjacent vertex i connected to v (a[v][i] == 1):\n3.   If i is not visited, recursively call DFS(i).\n4. Backtrack when no unvisited adjacent nodes remain.",
    "sampleInput": "4"
  },
  {
    "id": 13,
    "number": 13,
    "title": "Binary Search Algorithm",
    "category": "Searching",
    "timeComplexity": "O(log n)",
    "spaceComplexity": "O(1)",
    "aim": "Write a program to search the element in given array using Binary search algorithm.",
    "code": "#include<iostream.h>\n#include<conio.h>\nvoid main()\n{\n    int a[50],n,key,low,high,mid,found=0,i;\n    clrscr();\n    cout<<\"Enter number of elements: \";\n    cin>>n;\n    cout<<\"Enter elements in sorted order: \";\n    for(i=0;i<n;i++) cin>>a[i];\n    cout<<\"Enter element to search: \";\n    cin>>key;\n    low=0; high=n-1;\n    while(low<=high)\n    {\n        mid=(low+high)/2;\n        if(a[mid]==key)\n        {\n            cout<<\"Element found at position \"<<mid+1;\n            found=1;\n            break;\n        }\n        else if(a[mid]<key) low=mid+1;\n        else high=mid-1;\n    }\n    if(!found) cout<<\"Element not found\";\n    getch();\n}",
    "description": "Binary Search finds the position of a target value within a sorted array by repeatedly dividing the search interval in half.",
    "algorithmSteps": "1. Initialize low = 0, high = n-1.\n2. While low <= high:\n3.   mid = (low + high) / 2.\n4.   If a[mid] == key, found at mid+1.\n5.   If a[mid] < key, search right half: low = mid + 1.\n6.   Else search left half: high = mid - 1.\n7. If not found, report element not found.",
    "sampleInput": "10, 23, 35, 48, 62, 77, 91"
  },
  {
    "id": 14,
    "number": 14,
    "title": "Breadth First Search (BFS)",
    "category": "Graphs",
    "timeComplexity": "O(V\u00b2)",
    "spaceComplexity": "O(V)",
    "aim": "BFS Graph Traversal",
    "code": "#include<iostream.h>\n#include<conio.h>\nint a[10][10], visited[10], q[20];\nint n,front=-1,rear=-1;\nvoid bfs(int start)\n{\n    int i,v;\n    visited[start]=1;\n    q[++rear]=start;\n    while(front<rear)\n    {\n        v=q[++front];\n        cout<<v<<\" \";\n        for(i=0;i<n;i++)\n        if(a[v][i] && !visited[i])\n        {\n            visited[i]=1;\n            q[++rear]=i;\n        }\n    }\n}\nvoid main()\n{\n    int i,j,start;\n    clrscr();\n    cout<<\"Enter number of vertices: \";\n    cin>>n;\n    cout<<\"Enter adjacency matrix:\\n\";\n    for(i=0;i<n;i++)\n    for(j=0;j<n;j++)\n    cin>>a[i][j];\n    for(i=0;i<n;i++) visited[i]=0;\n    cout<<\"Enter starting vertex (0 to \"<<n-1<<\"): \";\n    cin>>start;\n    cout<<\"BFS traversal: \";\n    bfs(start);\n    getch();\n}",
    "description": "Breadth First Search (BFS) is a graph traversal algorithm that explores all neighbor nodes at the present depth before moving on to the nodes at the next depth level, using a Queue.",
    "algorithmSteps": "1. Mark start vertex as visited and push to queue.\n2. While queue is not empty:\n3.   Pop vertex v from front of queue and print it.\n4.   For all adjacent vertices i (a[v][i] == 1):\n5.     If i is not visited: mark visited and push into queue.",
    "sampleInput": "4"
  },
  {
    "id": 15,
    "number": 15,
    "title": "Circular Queue (Insert, Delete, Show)",
    "category": "Stacks & Queues",
    "timeComplexity": "O(1)",
    "spaceComplexity": "O(MAX)",
    "aim": "Write a program to implement circular queue with insert, delete and show operation.",
    "code": "#include<iostream.h>\n#include<conio.h>\n#define MAX 10\nint q[MAX],front=-1,rear=-1;\nvoid insert()\n{\n    int x;\n    if((rear+1)%MAX==front)\n    cout<<\"Circular Queue Overflow\";\n    else\n    {\n        cout<<\"Enter element: \";\n        cin>>x;\n        if(front==-1) front=rear=0;\n        else rear=(rear+1)%MAX;\n        q[rear]=x;\n    }\n}\nvoid del()\n{\n    if(front==-1)\n    cout<<\"Circular Queue Underflow\";\n    else\n    {\n        cout<<\"Deleted element: \"<<q[front];\n        if(front==rear) front=rear=-1;\n        else front=(front+1)%MAX;\n    }\n}\nvoid show()\n{\n    int i;\n    if(front==-1) cout<<\"Queue is empty\";\n    else\n    {\n        cout<<\"Queue: \";\n        i=front;\n        while(1)\n        {\n            cout<<q[i]<<\" \";\n            if(i==rear) break;\n            i=(i+1)%MAX;\n        }\n    }\n}\nvoid main()\n{\n    int ch;\n    clrscr();\n    do\n    {\n        cout<<\"\\n\\n1.Insert 2.Delete 3.Show 4.Exit\";\n        cout<<\"\\nEnter choice: \";\n        cin>>ch;\n        switch(ch)\n        {\n            case 1: insert(); break;\n            case 2: del(); break;\n            case 3: show(); break;\n        }\n    }while(ch!=4);\n    getch();\n}",
    "description": "A Circular Queue overcomes the limitation of a simple queue where vacant space before front cannot be utilized. Rear and Front wrap around to 0 using modulo arithmetic ((index + 1) % MAX).",
    "algorithmSteps": "1. Insert: If (rear + 1) % MAX == front -> Overflow. If front == -1 set front = rear = 0, else rear = (rear+1)%MAX. q[rear] = x.\n2. Delete: If front == -1 -> Underflow. Remove q[front]. If front == rear reset front = rear = -1, else front = (front+1)%MAX.\n3. Show: Traverse cyclically from front to rear.",
    "sampleInput": "10, 20, 30, 40, 50"
  },
  {
    "id": 16,
    "number": 16,
    "title": "Prim's Minimum Spanning Tree (MST)",
    "category": "Graphs",
    "timeComplexity": "O(V\u00b2)",
    "spaceComplexity": "O(V)",
    "aim": "2. Write a program to find minimum spanning tree using prims algorithm.",
    "code": "#include<iostream.h>\n#include<conio.h>\n#define INF 9999\nvoid main()\n{\n    int cost[10][10],selected[10]={0};\n    int n,i,j,edges=0,x,y,min,total=0;\n    clrscr();\n    cout<<\"Enter number of vertices: \";\n    cin>>n;\n    cout<<\"Enter cost adjacency matrix (0 for no edge):\\n\";\n    for(i=0;i<n;i++)\n    for(j=0;j<n;j++)\n    {\n        cin>>cost[i][j];\n        if(cost[i][j]==0) cost[i][j]=INF;\n    }\n    selected[0]=1;\n    cout<<\"Edges in MST:\\n\";\n    while(edges<n-1)\n    {\n        min=INF; x=y=0;\n        for(i=0;i<n;i++)\n        if(selected[i])\n        for(j=0;j<n;j++)\n        if(!selected[j] && cost[i][j]<min)\n        {\n            min=cost[i][j];\n            x=i; y=j;\n        }\n        cout<<x<<\" - \"<<y<<\" : \"<<min<<\"\\n\";\n        total+=min;\n        selected[y]=1;\n        edges++;\n    }\n    cout<<\"Minimum cost = \"<<total;\n    getch();\n}",
    "description": "Prim's Algorithm is a greedy algorithm that finds a Minimum Spanning Tree (MST) for a weighted undirected graph by starting with a single vertex and greedily adding the cheapest edge to an unvisited vertex.",
    "algorithmSteps": "1. Initialize selected[0] = 1, all others 0. edges = 0, total = 0.\n2. While edges < n-1:\n3.   Find minimum weight edge (i, j) where vertex i is selected and vertex j is NOT selected.\n4.   Add edge (i, j) to MST with cost min.\n5.   Mark selected[j] = 1, increment edges, total += min.\n6. Return total minimum cost.",
    "sampleInput": "4"
  },
  {
    "id": 17,
    "number": 17,
    "title": "Singly Linked List (Insert, Delete, Show)",
    "category": "Linked Lists",
    "timeComplexity": "O(n) Insert, O(1) Del",
    "spaceComplexity": "O(n)",
    "aim": "Write a program to implement single link list with insert, delete and show operation.",
    "code": "#include<iostream.h>\n#include<conio.h>\n#include<alloc.h>\nstruct node\n{\n    int data;\n    node *next;\n};\nnode *head=NULL;\nvoid insert()\n{\n    node *p;\n    p=(node*)malloc(sizeof(node));\n    cout<<\"Enter data: \";\n    cin>>p->data;\n    p->next=NULL;\n    if(head==NULL) head=p;\n    else\n    {\n        node *q=head;\n        while(q->next!=NULL) q=q->next;\n        q->next=p;\n    }\n}\nvoid del()\n{\n    node *p;\n    if(head==NULL)\n    cout<<\"List is empty\";\n    else\n    {\n        p=head;\n        head=head->next;\n        cout<<\"Deleted: \"<<p->data;\n        free(p);\n    }\n}\nvoid show()\n{\n    node *p=head;\n    if(p==NULL) cout<<\"List is empty\";\n    else\n    {\n        cout<<\"List: \";\n        while(p!=NULL)\n        {\n            cout<<p->data<<\" \";\n            p=p->next;\n        }\n    }\n}\nvoid main()\n{\n    int ch;\n    clrscr();\n    do\n    {\n        cout<<\"\\n\\n1.Insert 2.Delete 3.Show 4.Exit\";\n        cout<<\"\\nEnter choice: \";\n        cin>>ch;\n        switch(ch)\n        {\n            case 1: insert(); break;\n            case 2: del(); break;\n            case 3: show(); break;\n        }\n    }while(ch!=4);\n    getch();\n}",
    "description": "A Singly Linked List is a dynamic linear data structure composed of nodes. Each node contains a data field and a next pointer linking to the succeeding node.",
    "algorithmSteps": "1. Insert (at end): Allocate node p, set p->data = x, p->next = NULL. If head == NULL set head = p, else traverse to last node q and set q->next = p.\n2. Delete (from beginning): If head == NULL -> List empty. Set p = head, head = head->next, print p->data, free(p).\n3. Show: Traverse starting from head while p != NULL and print p->data.",
    "sampleInput": "12, 99, 37, 5"
  },
  {
    "id": 18,
    "number": 18,
    "title": "Doubly Linked List (Insert, Delete, Show)",
    "category": "Linked Lists",
    "timeComplexity": "O(n) Insert, O(1) Del",
    "spaceComplexity": "O(n)",
    "aim": "Doubly Linked List \u2013 Insert, Delete and Show",
    "code": "#include<iostream.h>\n#include<conio.h>\n#include<alloc.h>\nstruct node\n{\n    int data;\n    node *prev,*next;\n};\nnode *head=NULL;\nvoid insert()\n{\n    node *p,*q;\n    p=(node*)malloc(sizeof(node));\n    cout<<\"Enter data: \";\n    cin>>p->data;\n    p->prev=NULL;\n    p->next=NULL;\n    if(head==NULL) head=p;\n    else\n    {\n        q=head;\n        while(q->next!=NULL) q=q->next;\n        q->next=p;\n        p->prev=q;\n    }\n}\nvoid del()\n{\n    node *p;\n    if(head==NULL)\n    cout<<\"List is empty\";\n    else\n    {\n        p=head;\n        head=head->next;\n        if(head!=NULL) head->prev=NULL;\n        cout<<\"Deleted: \"<<p->data;\n        free(p);\n    }\n}\nvoid show()\n{\n    node *p=head;\n    if(p==NULL) cout<<\"List is empty\";\n    else\n    {\n        cout<<\"List: \";\n        while(p!=NULL)\n        {\n            cout<<p->data<<\" \";\n            p=p->next;\n        }\n    }\n}\nvoid main()\n{\n    int ch;\n    clrscr();\n    do\n    {\n        cout<<\"\\n\\n1.Insert 2.Delete 3.Show 4.Exit\";\n        cout<<\"\\nEnter choice: \";\n        cin>>ch;\n        switch(ch)\n        {\n            case 1: insert(); break;\n            case 2: del(); break;\n            case 3: show(); break;\n        }\n    }while(ch!=4);\n    getch();\n}",
    "description": "A Doubly Linked List has nodes containing two pointers: prev pointing to the predecessor node, and next pointing to the successor node. This enables bidirectional traversal.",
    "algorithmSteps": "1. Insert (at end): Allocate node p. Set p->prev = NULL, p->next = NULL. If head == NULL head = p. Else traverse to end q, set q->next = p, p->prev = q.\n2. Delete (from beginning): If head == NULL -> Empty. Set p = head, head = head->next. If head != NULL head->prev = NULL. Free(p).\n3. Show: Traverse and print from head to end.",
    "sampleInput": "101, 202, 303, 404"
  },
  {
    "id": 19,
    "number": 19,
    "title": "Binary Search Tree (Create, Delete, Show)",
    "category": "Trees",
    "timeComplexity": "O(log n) avg, O(n) worst",
    "spaceComplexity": "O(h)",
    "aim": "Write a program to implement Binary search tree with create, delete and show operation.",
    "code": "#include<iostream.h>\n#include<conio.h>\n#include<alloc.h>\nstruct node\n{\n    int data;\n    node *left,*right;\n};\nnode* create(int x)\n{\n    node *p=(node*)malloc(sizeof(node));\n    p->data=x; p->left=p->right=NULL;\n    return p;\n}\nnode* insert(node *root,int x)\n{\n    if(root==NULL) return create(x);\n    if(x<root->data) root->left=insert(root->left,x);\n    else if(x>root->data) root->right=insert(root->right,x);\n    return root;\n}\nnode* minNode(node *root)\n{\n    while(root->left!=NULL) root=root->left;\n    return root;\n}\nnode* del(node *root,int x)\n{\n    node *p;\n    if(root==NULL) return root;\n    if(x<root->data) root->left=del(root->left,x);\n    else if(x>root->data) root->right=del(root->right,x);\n    else\n    {\n        if(root->left==NULL)\n        {\n            p=root->right; free(root); return p;\n        }\n        if(root->right==NULL)\n        {\n            p=root->left; free(root); return p;\n        }\n        p=minNode(root->right);\n        root->data=p->data;\n        root->right=del(root->right,p->data);\n    }\n    return root;\n}\nvoid inorder(node *root)\n{\n    if(root!=NULL)\n    {\n        inorder(root->left);\n        cout<<root->data<<\" \";\n        inorder(root->right);\n    }\n}\nvoid main()\n{\n    node *root=NULL;\n    int ch,x;\n    clrscr();\n    do\n    {\n        cout<<\"\\n\\n1.Create/Insert 2.Delete 3.Show 4.Exit\";\n        cout<<\"\\nEnter choice: \";\n        cin>>ch;\n        switch(ch)\n        {\n            case 1: cout<<\"Enter value: \"; cin>>x;\n            root=insert(root,x); break;\n            case 2: cout<<\"Enter value: \"; cin>>x;\n            root=del(root,x); break;\n            case 3: cout<<\"BST (Inorder): \"; inorder(root); break;\n        }\n    }while(ch!=4);\n    getch();\n}",
    "description": "A Binary Search Tree (BST) is a binary tree where for each node, all values in its left subtree are smaller, and all values in its right subtree are greater.",
    "algorithmSteps": "1. Insert: If root == NULL return new node(x). If x < root->data, root->left = insert(root->left, x); else if x > root->data, root->right = insert(root->right, x).\n2. Delete: If x < root->data recurse left; if x > root->data recurse right. If match found: case 0/1 child return non-null child; case 2 children find inorder successor (min in right subtree), copy value, and delete successor.\n3. Show: Perform Inorder traversal (yields sorted sequence).",
    "sampleInput": "50, 30, 70, 20, 40, 60, 80"
  },
  {
    "id": 20,
    "number": 20,
    "title": "BST Traversals (Inorder, Preorder, Postorder)",
    "category": "Trees",
    "timeComplexity": "O(n)",
    "spaceComplexity": "O(h)",
    "aim": "BST Tree Traversals \u2013 Inorder, Preorder, Postorder",
    "code": "#include<iostream.h>\n#include<conio.h>\n#include<alloc.h>\nstruct node\n{\n    int data;\n    node *left,*right;\n};\nnode* insert(node *root,int x)\n{\n    node *p;\n    if(root==NULL)\n    {\n        p=(node*)malloc(sizeof(node));\n        p->data=x; p->left=p->right=NULL;\n        return p;\n    }\n    if(x<root->data) root->left=insert(root->left,x);\n    else root->right=insert(root->right,x);\n    return root;\n}\nvoid inorder(node *r)\n{\n    if(r!=NULL)\n    {\n        inorder(r->left); cout<<r->data<<\" \"; inorder(r->right);\n    }\n}\nvoid preorder(node *r)\n{\n    if(r!=NULL)\n    {\n        cout<<r->data<<\" \"; preorder(r->left); preorder(r->right);\n    }\n}\nvoid postorder(node *r)\n{\n    if(r!=NULL)\n    {\n        postorder(r->left); postorder(r->right); cout<<r->data<<\" \";\n    }\n}\nvoid main()\n{\n    node *root=NULL;\n    int n,i,x;\n    clrscr();\n    cout<<\"Enter number of nodes: \";\n    cin>>n;\n    cout<<\"Enter elements: \";\n    for(i=0;i<n;i++)\n    {\n        cin>>x;\n        root=insert(root,x);\n    }\n    cout<<\"Inorder: \";\n    inorder(root);\n    cout<<\"\\nPreorder: \";\n    preorder(root);\n    cout<<\"\\nPostorder: \";\n    postorder(root);\n    getch();\n}",
    "description": "Tree Traversals visit every node in a binary tree in a systematic order. The three classical depth-first traversals are Inorder, Preorder, and Postorder.",
    "algorithmSteps": "1. Inorder Traversal (L-N-R): Visit Left Subtree -> Visit Root Node -> Visit Right Subtree.\n2. Preorder Traversal (N-L-R): Visit Root Node -> Visit Left Subtree -> Visit Right Subtree.\n3. Postorder Traversal (L-R-N): Visit Left Subtree -> Visit Right Subtree -> Visit Root Node.",
    "sampleInput": "45, 25, 65, 15, 35, 55, 75"
  },
  {
    "id": 21,
    "number": 21,
    "title": "Array Operations (Insert, Delete, Display)",
    "category": "Arrays",
    "timeComplexity": "O(n) Insert/Delete",
    "spaceComplexity": "O(MAX)",
    "aim": "Array \u2013 Insert, Delete and Display",
    "code": "#include<iostream.h>\n#include<conio.h>\nvoid main()\n{\n    int a[50],n,i,pos,item,ch;\n    clrscr();\n    cout<<\"Enter number of elements: \";\n    cin>>n;\n    cout<<\"Enter elements: \";\n    for(i=0;i<n;i++) cin>>a[i];\n    do\n    {\n        cout<<\"\\n\\n1.Insert 2.Delete 3.Display 4.Exit\";\n        cout<<\"\\nEnter choice: \";\n        cin>>ch;\n        if(ch==1)\n        {\n            cout<<\"Enter position (1 to \"<<n+1<<\"): \";\n            cin>>pos;\n            cout<<\"Enter item: \";\n            cin>>item;\n            for(i=n;i>=pos;i--) a[i]=a[i-1];\n            a[pos-1]=item;\n            n++;\n        }\n        else if(ch==2)\n        {\n            cout<<\"Enter position: \";\n            cin>>pos;\n            if(pos>=1 && pos<=n)\n            {\n                for(i=pos-1;i<n-1;i++) a[i]=a[i+1];\n                n--;\n            }\n        }\n        else if(ch==3)\n        {\n            cout<<\"Array: \";\n            for(i=0;i<n;i++) cout<<a[i]<<\" \";\n        }\n    }while(ch!=4);\n    getch();\n}",
    "description": "Array Operations include Insertion (inserting an item at a specified position by shifting elements right) and Deletion (removing an item at a position by shifting elements left).",
    "algorithmSteps": "1. Insert at position pos (1 to n+1): Shift elements from index n down to pos rightwards (a[i] = a[i-1]), place item at a[pos-1], increment n.\n2. Delete at position pos: Shift elements from index pos-1 up to n-2 leftwards (a[i] = a[i+1]), decrement n.\n3. Display: Print elements from index 0 to n-1.",
    "sampleInput": "10, 20, 30, 40, 50"
  },
  {
    "id": 22,
    "number": 22,
    "title": "Radix Sort Algorithm",
    "category": "Sorting",
    "timeComplexity": "O(d \u00b7 (n + k))",
    "spaceComplexity": "O(n + k)",
    "aim": "Radix Sort",
    "code": "#include<iostream.h>\n#include<conio.h>\nint getMax(int a[],int n)\n{\n    int max=a[0],i;\n    for(i=1;i<n;i++)\n    if(a[i]>max) max=a[i];\n    return max;\n}\nvoid countSort(int a[],int n,int exp)\n{\n    int output[50],count[10]={0};\n    int i;\n    for(i=0;i<n;i++) count[(a[i]/exp)%10]++;\n    for(i=1;i<10;i++) count[i]+=count[i-1];\n    for(i=n-1;i>=0;i--)\n    {\n        output[count[(a[i]/exp)%10]-1]=a[i];\n        count[(a[i]/exp)%10]--;\n    }\n    for(i=0;i<n;i++) a[i]=output[i];\n}\nvoid main()\n{\n    int a[50],n,i,max,exp;\n    clrscr();\n    cout<<\"Enter number of non-negative elements: \";\n    cin>>n;\n    cout<<\"Enter elements: \";\n    for(i=0;i<n;i++) cin>>a[i];\n    max=getMax(a,n);\n    for(exp=1;max/exp>0;exp*=10)\n    countSort(a,n,exp);\n    cout<<\"Sorted array: \";\n    for(i=0;i<n;i++) cout<<a[i]<<\" \";\n    getch();\n}",
    "description": "Radix Sort is a non-comparative sorting algorithm that sorts numbers digit by digit starting from the least significant digit (LSD) to the most significant digit (MSD) using Counting Sort as a stable subroutine.",
    "algorithmSteps": "1. Find maximum number in array to determine number of digits.\n2. For each exponent exp = 1, 10, 100, ... while max / exp > 0:\n3.   Apply Counting Sort based on the digit at position (a[i] / exp) % 10.\n4. Array is completely sorted after all digit passes.",
    "sampleInput": "170, 45, 75, 90, 802, 24, 2, 66"
  }
];
